### PR TITLE
Add a preserveTapToClose prop

### PR DESCRIPTION
**Pull request by robcalcroft**
When `showCancel` is set, you cannot tap to close the message, this allows you to override that functionality.

### CODE REVIEW

**Comment by testshallpass** [comment]
Hi @robcalcroft Thanks for the PR. Can you use existing `tapToCloseEnabled` prop instead? It looks like I might have forgotten to add it to this condition/use case.

**Comment by robcalcroft** [comment]
@testshallpass yeh that's why I made this PR, I wasn't sure whether you had other plans for `tapToCloseEnabled`, very happy for the fix to be adding `tapToCloseEnabled` into the conditional i've modified in my PR?

**Comment by robcalcroft** [comment]
Could that change affect anyone using the current `tapToCloseEnabled`? Would this change require a larger version bump?

**Comment by testshallpass** [comment]
hi @robcalcroft  Yeah good point it does have potential to adversely affect others but I think it's low. If `tapToCloseEnabled` usage is changed definitely be a minor/major bump up. I think it need to be communicated that to properly have cancel and no other dismiss actions then it need to be configured using `tapToCloseEnabled` and `panResponderEnabled` if this is the desired use case.

**Pull request closed without merging**
