### PR TITLE
Add elevation props

### PR DESCRIPTION
**Pull request by kevinresol**
Fixes https://github.com/testshallpass/react-native-dropdownalert/issues/70

### CODE REVIEW

**Comment by kevinresol** [comment]
Got this when running `jest --updateSnapshot`
```
TypeError: Path must be a string. Received [ '/Users/kevin/Codes/react-native-dropdownalert' ]
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at readRawConfig (/Users/kevin/Codes/react-native-dropdownalert/node_modules/jest-config/build/index.js:49:31)
    at readConfig (/Users/kevin/Codes/react-native-dropdownalert/node_modules/jest-config/build/index.js:20:1)
    at runCLI (/Users/kevin/Codes/react-native-dropdownalert/node_modules/jest-cli/build/jest.js:51:3)
    at Object.run (/Users/kevin/.config/yarn/global/node_modules/jest-cli/build/cli/index.js:40:3)
    at Object.<anonymous> (/Users/kevin/.config/yarn/global/node_modules/jest-cli/bin/jest.js:14:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by testshallpass** [comment]
It could be a version issue with Node, jest-cli or jest. Can you specify the versions you have installed?

**Comment by kevinresol** [comment]
node 8.2.1 
jest 19.0.2

**Comment by testshallpass** [comment]
Those look good. what's the jest-cli version?

**Comment by kevinresol** [comment]
it is also 19.0.2

**Comment by kevinresol** [comment]
Well, It works when I use `npm test`
Maybe something is mixed up with my global installation

**Comment by kevinresol** [comment]
alright it is updated

**Pull request merged**
