### PR TITLE
Add useNativeDriver prop

### PR DESCRIPTION
**Pull request by lucianomlima**
Allow users to decide to disable or not native driver for animations.

### CODE REVIEW

**Comment by testshallpass** [comment]
Hi @lucianomlima let's make useNativeDriver default: `IS_IOS`. Also, it had undesired results on Android. Do you if this been resolved in later react-native versions?

**Comment by lucianomlima** [comment]
@testshallpass Can tell me what undesired results have on Android? And for which RN version?
I'm testing here with RN 0.49.5 and it's working fine!

**Comment by testshallpass** [comment]
So there was a bug reported about animation not working. issue #65

**Comment by testshallpass** [comment]
No, I mean the `useNativeDriver` defaultProps set to IS_IOS to keep backwards compatibility. A nice note about poor performance in earlier react-native versions is good too.

**Comment by lucianomlima** [comment]
Done!

**Comment by lucianomlima** [comment]
Sorry, I forget to put a note about enable useNativeDriver for Android. Now is truely done!

**Pull request merged**
