### PR TITLE
Add & use react-native-vector-icons

### PR DESCRIPTION
**Pull request by erhanbicer**

### CODE REVIEW

**Comment by testshallpass** [comment]
@erhanbicer Thanks so much. I have recently refactored and will rework your changes.

**Comment by testshallpass** [comment]
I was also thinking that if you wanted to use `react-native-vector-icons` you could use `renderImage` prop to do so and include the dependency in the project.

**Comment by ardyfeb** [comment]
For dynamic icons, we can use https://github.com/WrathChaos/react-native-dynamic-vector-icons

**Comment by EyMaddis** [comment]
I think that would add unnecessary bloat to applications that do not use vector icons. Especially considering that this is a native dependency, breaking web support.

It would be easy to pass a `renderImage` function to achieve the same effect.

**Pull request closed without merging**
