### PR TITLE
Added payload to alertWithType() passed down to onClose()

### PR DESCRIPTION
**Pull request by rdewolff**
This fixes the issue https://github.com/testshallpass/react-native-dropdownalert/issues/177.

### CODE REVIEW

**Comment by rdewolff** [comment]
What do you think @testshallpass ?

**Comment by justinobney** [comment]
@rdewolff I think this is a must to make handling onClose viable. That or passing in an `onClose` callback to `alertWithType`

**Comment by rdewolff** [comment]
Can you merge test and merge this PR?

**Comment by rdewolff** [comment]
nice! New release can be made ✨ 🎉

**Pull request merged**
