### PR TITLE
refactor(state): pass in the state to the render title/message so tha…

### PR DESCRIPTION
**Pull request by sahanatroam**
…t the message can be used to render title/message

### CODE REVIEW

**Comment by sahanatroam** [comment]
@testshallpass is this something you think worth adding in ?

**Comment by drewandre** [comment]
This has been very helpful! We were having an issue where if the user increased the ios system font size, it would blow the title and message font sizes on the dropdown way out of proportion. The options were either add an `allowFontScaling` prop to the dropdown, or be able to customize the title and message. Without access to the dropdown's state, which holds the actual title and message, we wouldn't be able to create a custom title and message with that prop. Thanks @sahanatroam

**Comment by testshallpass** [comment]
@sahanatroam I have approved and this addresses #124.

**Comment by sahanatroam** [comment]
Awesome @testshallpass when are you planning to release this ?

**Comment by testshallpass** [comment]
@sahanatroam Today, v3.7.1

**Comment by sahanatroam** [comment]
🎉

**Pull request merged**
